spring.application.name=API-GATEWAY

server.servlet.context-path=/api
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.config.import=optional:file:.env[.properties]
secretKey=${JWT_SECRET_KEY}

# Admin Service Routing
spring.cloud.gateway.server.webmvc.routes[0].id=admin-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/admin/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1


# Auth Service Routing
spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# Auth Service Routing
spring.cloud.gateway.server.webmvc.routes[2].id=flight-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://FLIGHT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=path=/flight/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1