spring.application.name=apigateway

server.servlet.context-path=/api
server.port=8085

spring.config.import=optional:file:.env[.properties]
secretKey=${JWT_SECRET_KEY}

# Admin Service Routing
spring.cloud.gateway.server.webmvc.routes[0].id=admin-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/admin/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1


# Auth Service Routing
spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1