spring.application.name=BOOKING-SERVICE

server.servlet.context-path=/booking
server.port = 9000


springdoc.swagger-ui.path=/swagger-ui/index.html

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

secretKey=${JWT_SECRET_KEY}