spring.application.name=flight-booking-system-admin-service
server.servlet.context-path=/flight-booking-system-admin-service
springdoc.swagger-ui.path=/swagger-ui/index.html

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

secretKey=${JWT_SECRET_KEY}